Bug fixed for u<0
danieljprice/phantom pull request #167
Opened 2021-08-31 07:20 UTC by Fitz-Hu

Bug fixed for u<0
Add star density profile option in grtde
Putting star on parabolic orbit in moddump_tidal

2021-08-31 08:19 UTC, jameswurster commented
Please check to ensure that your change to the cooling timestep does not have unintended consequences, such as making the Sedov test impossibly slow (as noted in the comment you deleted).  I recently added an optional thermal floor as a work-around to prevent u < 0 since timestep modifications (including the one you committed) was not sufficient for rapidly evolving regions.

Please also be cautious when making a change that will affect many groups, such as changing the default units in a setup file.  Since this setup is widely used, it would be safer to prompt the choice of units rather than force GR units on everyone.

2021-09-01 00:45 UTC, danieljprice requested changes
@jameswurster including the cooling timestep does indeed solve the problem we were having with u < 0 in rapidly expanding regions, and we don't want to enforce a temperature floor for this case. We added a condition so that the sedov test should still run ok, i.e. we tests for u > tiny so as not to end up with dtcool= 0

2021-09-01 00:45 UTC, danieljprice commented on src/setup/setup_star.f90
>   ! set up particles
see comment by James -- we should not make geometric units the default here!!

2021-09-01 00:45 UTC, danieljprice commented on src/setup/setup_star.f90
>   ! set up particles
probably best just to leave this line commented out so the default units are as previously

2021-09-01 00:45 UTC, danieljprice commented on src/utils/moddump_tidal.f90
> +=======
this is the cause of the build failure, just some of the git conflicts caused by code merge
i.e. get rid of the <<<< HEAD and ===== and just leave the line that you want here

2021-09-01 00:45 UTC, danieljprice commented on src/utils/moddump_tidal.f90
same with this one, just delete the >>>> here

2021-09-01 07:56 UTC, jameswurster commented
@danieljprice thanks for the clarification regarding the timestep.  My previous tests were detrimental to Sedov (hence the comment), but I think I was using epsilon rather than tiny for both f & u.

2021-09-23 03:08 UTC, danieljprice approved these changes

2021-10-05 06:18 UTC, merged