Dynamic Boundaries; clump finding analysis; cloud-cloud collision setup
danieljprice/phantom pull request #398
Opened 2023-04-03 17:55 UTC by jameswurster

Type of PR: 
New numerical algorithms
New analysis routines

Description:
This PR contains all the algorithms required for Wurster & Bonnell (2023).  This includes
-Dynamic boundaries
-a new clump-finding algorithm
-a new setup routine to collide two clouds

Testing:
Extensive testing prior to performing the study of Wurster & Bonnell (2023)
ran the testsuite for good measure.

Did you run the bots? yes

2023-04-03 21:58 UTC, jameswurster commented
@danieljprice , it looks like the failures are due to the workflow not being able to download the proper libraries or compilers...

2023-04-25 09:46 UTC, jameswurster commented
@danieljprice , I hope that this merge didn't mess up anything.  The delay in accepting my PR caused a merge conflict when I wanted to update something, so I followed the instructions on the screen.  While I think all of your changes have been kept, I hope that some of my tests & temporary code has not been merged as well.

2023-04-25 11:27 UTC, jameswurster commented
Not sure if the failed checks are a result of my merge or the pipeline.

2023-04-26 10:55 UTC, jameswurster commented
This looks like a pipeline failure where it could not connect to required sites.

2023-04-28 06:25 UTC, danieljprice commented
sorry my fault for the delay here, I was trying to push some other things through the pipeline that I knew would give some conflicts...

2023-04-28 06:28 UTC, danieljprice commented
but some of the build failures are genuine: we no longer allow compiler warnings in phantom on master, so it's complaining about a few warnings being added (e.g. in moddump), which need to be cleaned up:

```
Error: ‘fdg_inclean$’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

2023-04-28 06:46 UTC, danieljprice requested changes
Sorry for the delay, and thanks for the contributions. Code itself looks good, but would be much neater if we can shift all functionality related to dynamic boundaries into a single module (e.g. called boundary_dynamic.f90) rather than having the functionality distributed throughout the code. I dropped a few comments in specific places where things can be moved to such a module. This would help a lot with maintenance and testing. Cheers.

2023-04-28 06:46 UTC, danieljprice commented on src/main/readwrite_dumps_fortran.F90
> + call extract('irho_bkg_ini',irho_bkg_ini,hdr,ierrs(1))
please can you put an if (dynamic_bdy) around these extract calls?

2023-04-28 06:46 UTC, danieljprice commented on src/main/boundary.f90
>  !
it would be neater here to make a fresh module called boundary_dynamic.f90 that contains all the functionality for dynamic boundaries rather than mixing it with the existing functionality in boundary.f90

2023-04-28 06:46 UTC, danieljprice commented on src/main/boundary.f90
> +!-----------------------------------------------------------------------
all the above routines can be shifted in to a boundary_dynamic.f90 module

2023-04-28 06:46 UTC, danieljprice commented on src/main/checksetup.F90
> +          if (xyzh(1,i) < xmin) xyzh(1,i) = xyzh(1,i) + dxbound
please add a short subroutine called something like "adjust_particles_dynamic_boundary" that is in your boundary_dynamic.f90 module and make this a one-liner here

2023-04-28 06:46 UTC, danieljprice commented on src/main/energies.F90
> +          ! determine the particle whose density is closest to the original background
this is a giant chunk of code inside energies, please can it be shifted to a subroutine from your boundary_dynamic.f90 module that takes xi,yi,zi as input and gives the required outputs, hence reducing this to a single subroutine call?

2023-04-28 06:46 UTC, danieljprice commented on src/main/energies.F90
> +          xyz_n_all(1) = min(xyz_n_all(1),xi)
similarly, another short subroutine here (inside boundary_dynamic.f90) would greatly declutter this

2023-04-28 06:46 UTC, danieljprice commented on src/main/initial.F90
> +    if (irho_bkg_ini > 0.) then
suggest to incorporate this into the init_dynamic_bdy() routine, or if not possible create another short subroutine that can be called here, keeping the actual implementation details inside boundary_dynamic.f90

2023-04-28 06:46 UTC, danieljprice commented on src/main/step_leapfrog.F90
> + if (dynamic_bdy) then
suggest to add another short subroutine here called step_dynamic_boundary that is placed inside the boundary_dynamic.f90 module

2023-04-28 15:53 UTC, jameswurster commented
@danieljprice as requested, dynamic boundaries are now in their own module.

2023-05-01 02:01 UTC, danieljprice approved these changes
new module looks great, thanks James!

2023-05-01 02:09 UTC, danieljprice commented
PS: to fix the conflicts in the authors file:
```
cd phantom/scripts
./bots.sh --only authors --commit
```

2023-05-01 02:12 UTC, merged