Libphantom-amuse
danieljprice/phantom pull request #513
Opened 2024-02-22 09:43 UTC by rieder

Type of PR: 
new code: library for using Phantom with AMUSE

Description:
- introduce a `write_files` option, defaults to `.true.`
- make write/open/close statements conditional on `write_files`
- introduce `utils/libphantom-amuse.F90`, with helper subroutines for the AMUSE interface

Testing:
WIP

Did you run the bots? yes/no

Did you update relevant documentation in the docs directory? yes/no

2024-10-04 06:31 UTC, danieljprice requested changes

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> + call set_units(dist=1 * au,mass=1.*solarm,G=1.)
one option here is to send strings for the units, then call select_unit(mass_unit,umass,ierr) to get the unit from the string

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> + call set_units(dist=1 * au,mass=1.*solarm,G=1.)
this is inside setup/set_units.f90

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +subroutine amuse_initialize_code()
can we delete this if obsolete?

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +subroutine amuse_set_phantom_option(name, valstring, imatch)
this could in principle be done in a more automated way, if we were to read the infile like setup files... this is on my list (should create an issue on this to get this task done)

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +            eos_vars,metrics,pxyzu,rad
I think you can just call get_derivs_global() here which calls derivs, then the interface to derivs would not need updating. This can be found in the derivs module and is used in the test suite

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +            if (xyzh(4,i)  >  0.) then
this condition should be a call to isdead_or_accreted(xyzh(4,i)) for consistency with the other code

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> + use io,               only:iprint,iwritein,id,master,iverbose,&
this should be removed and replaced by a call to evol but with some flags needed for amuse to behave correctly

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +        ! Sink particles can't be killed - so we just set its mass to zero
sink particles can be killed by giving them a negative mass, suggest xyzmh_ptmass(4,i) = -abs(xyzmh_ptmass(4,i))

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +subroutine amuse_get_unit_length(unit_length_out)
should not be a need for these routines, as long as set_units() is called during the amuse_initialize_code_new routine, and if you can send strings to set different options

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +subroutine amuse_evolve_model(tmax_in)
see previous, should be just a call to evolve

2024-10-04 06:31 UTC, danieljprice commented on src/utils/libphantom-amuse.F90
> +! End of Getters
please delete commented out/ obsolete code

2025-07-22 14:30 UTC, rieder commented on src/utils/libphantom-amuse.F90
> +        ! Sink particles can't be killed - so we just set its mass to zero
done

2025-07-22 14:33 UTC, rieder commented on src/utils/libphantom-amuse.F90
> +            eos_vars,metrics,pxyzu,rad
changed

2025-07-22 14:34 UTC, rieder commented on src/utils/libphantom-amuse.F90
> +            if (xyzh(4,i)  >  0.) then
done

2025-07-22 14:34 UTC, rieder commented on src/utils/libphantom-amuse.F90
> +subroutine amuse_initialize_code()
done

2025-07-24 12:13 UTC, rieder commented on src/utils/libphantom-amuse.F90
> + use io,               only:iprint,iwritein,id,master,iverbose,&
Done

2025-07-24 12:14 UTC, rieder commented on src/utils/libphantom-amuse.F90
> +subroutine amuse_evolve_model(tmax_in)
done

2025-07-24 12:15 UTC, rieder commented
I think I tackled all the issues, just some whitespace diff remains that I did not intend.

2025-07-24 12:15 UTC, rieder commented
Ready to merge for me.

2025-07-28 14:25 UTC, rieder commented
Made some changes to `libphantom-amuse` for consistency with AMUSE, which uses 32-bit integers for particle indices instead of the 64-bit integers Phantom uses (see https://github.com/amusecode/amuse/issues/1077). The interface will now stop with an Error if this would cause a problem. Also gets rid of some warnings when the AMUSE interface is compiled.

2025-08-01 15:45 UTC, danieljprice commented
Hi Steven, I tracked down what is causing the build failures, there's a duplicated cleanlibphantom target in build/Makefile, which I think should be cleanlibphantomamuse for your case

2025-08-09 16:54 UTC, merged